//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nanoFramework_Matter.h"
#include "nanoFramework_Matter_nanoFramework_Matter_Math.h"

using namespace nanoFramework_Matter::nanoFramework_Matter;


HRESULT Library_nanoFramework_Matter_nanoFramework_Matter_Math::NativeSquare___STATIC__R8__R8( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        double param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 0, param0 ) );

        double retValue = Math::NativeSquare( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_double( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
