//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef NANOFRAMEWORK_MATTER_H
#define NANOFRAMEWORK_MATTER_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_nanoFramework_Matter_nanoFramework_Matter_Math
{
    NANOCLR_NATIVE_DECLARE(NativeSquare___STATIC__R8__R8);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Matter;

#endif // NANOFRAMEWORK_MATTER_H
