//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nanoFramework_Matter.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_nanoFramework_Matter_nanoFramework_Matter_Math::NativeSquare___STATIC__R8__R8,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Matter =
{
    "nanoFramework.Matter",
    0x3B39FDCB,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
